const PARK_MAGIC_KINGDOM = {
  name: "Magic Kingdom",
  attractions: [
    { park: "Magic Kingdom", land: "Main Street, U.S.A.",  name: "Railroad" },
    { park: "Magic Kingdom", land: "Adventureland",        name: "Pirates" },
    { park: "Magic Kingdom", land: "Adventureland",        name: "Jungle Cruise" },
    { park: "Magic Kingdom", land: "Adventureland",        name: "Magic Carpets" },
    { park: "Magic Kingdom", land: "Adventureland",        name: "Tiki Room" },
    { park: "Magic Kingdom", land: "Adventureland",        name: "Swiss Treehouse" },
    { park: "Magic Kingdom", land: "Frontierland",         name: "Big Thunder" },
    { park: "Magic Kingdom", land: "Frontierland",         name: "Tiana's Bayou" },
    { park: "Magic Kingdom", land: "Frontierland",         name: "Country Bears" },
    { park: "Magic Kingdom", land: "Liberty Square",       name: "Haunted Mansion" },
    { park: "Magic Kingdom", land: "Liberty Square",       name: "Hall of Presidents" },
    { park: "Magic Kingdom", land: "Fantasyland",          name: "Small World" },
    { park: "Magic Kingdom", land: "Fantasyland",          name: "Peter Pan" },
    { park: "Magic Kingdom", land: "Fantasyland",          name: "Carrousel" },
    { park: "Magic Kingdom", land: "Fantasyland",          name: "PhilharMagic" },
    { park: "Magic Kingdom", land: "Fantasyland",          name: "Winnie the Pooh" },
    { park: "Magic Kingdom", land: "Fantasyland",          name: "Mad Tea Party" },
    { park: "Magic Kingdom", land: "Fantasyland",          name: "Seven Dwarfs Mine Train" },
    { park: "Magic Kingdom", land: "Fantasyland",          name: "Little Mermaid" },
    { park: "Magic Kingdom", land: "Fantasyland",          name: "Enchanted Tales w/ Belle" },
    { park: "Magic Kingdom", land: "Fantasyland",          name: "Dumbo" },
    { park: "Magic Kingdom", land: "Fantasyland",          name: "Barnstormer" },
    { park: "Magic Kingdom", land: "Fantasyland",          name: "Casey Jr. Splash" },
    { park: "Magic Kingdom", land: "Tomorrowland",         name: "Astro Orbiter" },
    { park: "Magic Kingdom", land: "Tomorrowland",         name: "Buzz Lightyear" },
    { park: "Magic Kingdom", land: "Tomorrowland",         name: "PeopleMover" },
    { park: "Magic Kingdom", land: "Tomorrowland",         name: "Space Mountain" },
    { park: "Magic Kingdom", land: "Tomorrowland",         name: "Speedway" },
    { park: "Magic Kingdom", land: "Tomorrowland",         name: "TRON" },
    { park: "Magic Kingdom", land: "Tomorrowland",         name: "Carousel of Progress" },
    { park: "Magic Kingdom", land: "Tomorrowland",         name: "Laugh Floor" },
  ]
};
